### ISSUE TITLE
pybtex version outdated

### ISSUE THREAD

**Issue by traits** [VorpalBlade/pelican-cite#21]
This project requires pybtex < 0.23.0, which requires the following in its `__init__.py`: 

`from collections import Mapping`  

This is incompatible with newer Python versions (https://stackoverflow.com/a/69727802)

**Comment by VorpalBlade** [comment]
Um, why did you close this? I haven't had time to look at this yet (I don't use pelican much any more, my website updates very rarely).

**Comment by traits** [comment]
I'll close this. The requirement comes from another incarnation of pelican-cite. 

The plugin situation for Pelican is abysmal. For this plugin alone exist at least 3 repositories with the same or similar (underscores, hyphens) names. 

Not yet talked about the migration of old Pelican plugins and the references in the various 'official' umbrella repos to specific SHA's of the actual plugin repos - kind of poor man git submodules - which has not been completed for many years.

> Um, why did you close this? I haven't had time to look at this yet (I don't use pelican much any more, my website updates very rarely).

You were too fast ;). I didn't finish the comment for the close yet.
